name: Build Containers

# Global minimal permissions (can be overridden by job-level permissions)
permissions:
  contents: read

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'infrastructure/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'infrastructure/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      infrastructure: ${{ steps.changes.outputs.infrastructure }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            infrastructure:
              - 'infrastructure/**'

  build-backend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate image name
        id: image-name
        run: |
          # Convert repository name to lowercase for Docker registry compatibility
          echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Check if backend Docker files exist
        id: check-backend-docker
        run: |
          if [ -f "backend/docker/Dockerfile.dev" ] && [ -f "backend/docker/Dockerfile.prod" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push backend dev image
        if: steps.check-backend-docker.outputs.exists == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/docker/Dockerfile.dev
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.image-name.outputs.name }}/backend:dev-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backend prod image
        if: steps.check-backend-docker.outputs.exists == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/docker/Dockerfile.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.image-name.outputs.name }}/backend:prod-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Skip backend (Docker files not ready)
        if: steps.check-backend-docker.outputs.exists == 'false'
        run: |
          echo "Backend Docker files not yet implemented - skipping build"

  build-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate image name
        id: image-name
        run: |
          # Convert repository name to lowercase for Docker registry compatibility
          echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Check if frontend Docker files exist
        id: check-frontend-docker
        run: |
          if [ -f "frontend/docker/Dockerfile.dev" ] && [ -f "frontend/docker/Dockerfile.prod" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push frontend dev image
        if: steps.check-frontend-docker.outputs.exists == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/docker/Dockerfile.dev
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.image-name.outputs.name }}/frontend:dev-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend prod image
        if: steps.check-frontend-docker.outputs.exists == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/docker/Dockerfile.prod
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.image-name.outputs.name }}/frontend:prod-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Skip frontend (Docker files not ready)
        if: steps.check-frontend-docker.outputs.exists == 'false'
        run: |
          echo "Frontend Docker files not yet implemented - skipping build"

  build-infrastructure:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.infrastructure == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Docker Compose files
        run: |
          cd infrastructure
          # Check which docker-compose files exist and validate them
          if [ -f "docker/docker-compose.base.yml" ]; then
            echo "Validating base configuration..."
            docker compose -f docker/docker-compose.base.yml config --quiet
          fi
          if [ -f "docker/docker-compose.dev.yml" ]; then
            echo "Validating dev configuration..."
            docker compose -f docker/docker-compose.dev.yml config --quiet
          fi
          if [ -f "docker/docker-compose.test.yml" ]; then
            echo "Validating test configuration..."
            docker compose -f docker/docker-compose.test.yml config --quiet
          fi
          if [ -f "docker/docker-compose.prod.yml" ]; then
            echo "Validating prod configuration..."
            docker compose -f docker/docker-compose.prod.yml config --quiet
          fi

      - name: Test infrastructure setup
        run: |
          echo "Infrastructure validation completed successfully"